### ISSUE TITLE
怎么不能连线？有没有API

### ISSUE THREAD

**Issue by oozm** [OXOYO/X-Flowchart-Vue#1]
怎么不能连线？有没有API

**Comment by OXOYO** [comment]
@zhaojianshu 没有API，这是从项目中抽取出来的，不能连线看看是不是有报错，或者提供个测试地址看看。

**Comment by oozm** [comment]
大神，我想把你这个嵌入到我的项目中，是否可以指导下。谢谢了！！

**Comment by OXOYO** [comment]
嵌吧，咋嵌自己看看代码，很简单的。
