### ISSUE TITLE
编辑边的属性时候 会导致边不可见

### ISSUE THREAD

**Issue by mylvlin** [OXOYO/X-Flowchart-Vue#11]
## Befor
![image](https://user-images.githubusercontent.com/6387913/68098760-987ab080-fef9-11e9-8530-0ca02d62cddc.png)

## Input
![image](https://user-images.githubusercontent.com/6387913/68098787-bc3df680-fef9-11e9-9176-ae53c4fd2afc.png)

##  After
![image](https://user-images.githubusercontent.com/6387913/68098808-d37ce400-fef9-11e9-9f94-3abe470419da.png)

**Comment by OXOYO** [comment]
了解，最近没什么时间搞这个，你可以试着修复下，欢迎PR。

**Comment by OXOYO** [comment]
@mylvlin 已修复。
