### ISSUE TITLE
撤销 重做 清空操作日志BUG

### ISSUE THREAD

**Issue by lzygit18** [OXOYO/X-Flowchart-Vue#13]
1 撤销时 会出现清空画布的情况
重现方式：添加一个node节点，清空操作日志，再添加一个node节点，撤销，两个都不见了
2 清空操作日志
清空操作日志，应该清空操作记录，但是需要保留当前画布内容，并且不可撤销
3 撤销 和 重做 使用时 容易出现错乱
操作5条记录后，撤销2条记录，在操作一条记录（这个记录应该先清除撤销的两条，在家这一条（第条））

**Comment by AmySay** [comment]
大佬，早日更新啊
