### ISSUE TITLE
第二行第二个元素正圆形的锚点有问题

### ISSUE THREAD

**Issue by loongmxbt** [OXOYO/X-Flowchart-Vue#17]
![image](https://user-images.githubusercontent.com/5986600/71705438-c22d5680-2e1a-11ea-92b3-3258bda4b804.png)
红色锚点只有最右边，其他为蓝色点，并且不在边上，连接起来就变成这样了。
![image](https://user-images.githubusercontent.com/5986600/71705458-db360780-2e1a-11ea-8e93-9ed01bb794e9.png)

**Comment by OXOYO** [comment]
已知BUG，还在解决中

**Comment by OXOYO** [comment]
fixed
