### ISSUE TITLE
官网的版本，bug

### ISSUE THREAD

**Issue by cmdares** [OXOYO/X-Flowchart-Vue#18]
http://oxoyo.co/X-Flowchart-Vue/
箭头存在bug，如图
![image](https://user-images.githubusercontent.com/5292190/75035005-71b4aa00-54e9-11ea-9840-d6cde4c75a5f.png)
从箭头的栏目中，第四行，第二个开始，托追出来的就都是圆圈了。
请关注下，谢谢。

**Comment by OXOYO** [comment]
箭头还没有全部画完，所以没画的图形拖出来都是默认的圆形。各种图形会逐步补齐。
