### ISSUE TITLE
为啥起不来？好像包找不到

### ISSUE THREAD

**Issue by Roonie1** [OXOYO/X-Flowchart-Vue#19]
![image](https://user-images.githubusercontent.com/10750556/75759986-6b3bf300-5d71-11ea-9f5d-cefad1afde59.png)

**Comment by yinbowen** [comment]
我也遇到了同样的问题，下载这些包也下载不成功。

**Comment by Roonie1** [comment]
我解决了，install @antv/g6@3.1.3
![image](https://user-images.githubusercontent.com/10750556/75842726-1ac5a380-5e0c-11ea-8992-118e2cf79fb8.png)
