### ISSUE TITLE
请教大佬一个问题，我想在自己一个项目的模块里把这个写进去应该如何操作？

### ISSUE THREAD

**Issue by zhongnan1990** [OXOYO/X-Flowchart-Vue#21]
我现在有一个后台管理项目下面的一个页面里想导入这个项目使用，但这个打包后是一个单独的项目，应该不可以直接引用到项目里，想请教下这个该如何集成进项目使用，或许我的思路都是错的，希望大佬可以大致说一下应该以何种方式引入？或者指明下思路或者方向？非常感谢！！

**Comment by OXOYO** [comment]
这是一个G6的实践，目前还没考虑做成库的形式，本项目是MIT协议，可以考虑直接引源码，或者直接用G6最新版去开发。

**Comment by zhongnan1990** [comment]
> 这是一个G6的实践，目前还没考虑做成库的形式，本项目是MIT协议，可以考虑直接引源码，或者直接用G6最新版去开发。

了解了 非常感谢!
