### ISSUE TITLE
目前性能太低，还没发用到真实场景中，请问有没有升级计划

### ISSUE THREAD

**Issue by baiyicanggou** [OXOYO/X-Flowchart-Vue#24]
我做过性能测试，复制100多个节点，基本就卡死了
我也研究了wfd-vue，他几百个节点也没问题，都是用的g6的3.1版本
但是咱们这个功能特别强大，如果性能上来，就非常完美了

**Comment by OXOYO** [comment]
:joy:近期会优化，考虑升级G6到最新版，可能改动比较大，性能应该会有较大提升。

**Comment by baiyicanggou** [comment]
棒棒哒，期待！祝早日完成奥！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "葡萄干@吐鲁番"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 上午9:49
收件人: "OXOYO/X-Flowchart-Vue"<X-Flowchart-Vue@noreply.github.com&gt;; 
抄送: "27193847"<27193847@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OXOYO/X-Flowchart-Vue] 目前性能太低，还没发用到真实场景中，请问有没有升级计划 (#24)





 
😂近期会优化，考虑升级G6到最新版，可能改动比较大，性能应该会有较大提升。
