### ISSUE TITLE
怎么自定义节点

### ISSUE THREAD

**Issue by zwhrcx0612** [OXOYO/X-Flowchart-Vue#27]
我想用iconfont上的图标作为节点，但是path是这样的
![image](https://user-images.githubusercontent.com/34915727/84367098-54295e80-ac06-11ea-83f7-a8b0f859a4ba.png)
怎么才能弄成这样的：
![image](https://user-images.githubusercontent.com/34915727/84367186-715e2d00-ac06-11ea-8cbf-32f402595cbb.png)

**Comment by zwhrcx0612** [comment]
大佬的图标都是自己手动画的吗

**Comment by OXOYO** [comment]
> 我想用iconfont上的图标作为节点，但是path是这样的
> ![image](https://user-images.githubusercontent.com/34915727/84367098-54295e80-ac06-11ea-83f7-a8b0f859a4ba.png)
> 怎么才能弄成这样的：
> ![image](https://user-images.githubusercontent.com/34915727/84367186-715e2d00-ac06-11ea-8cbf-32f402595cbb.png)
图裂了

**Comment by OXOYO** [comment]
> 大佬的图标都是自己手动画的吗

目前的元素都是自定义节点或自定义边，每个图形都有自己的path计算规则。

**Comment by OXOYO** [comment]
> 我想用iconfont上的图标作为节点，但是path是这样的
> ![image](https://user-images.githubusercontent.com/34915727/84367098-54295e80-ac06-11ea-83f7-a8b0f859a4ba.png)
> 怎么才能弄成这样的：
> ![image](https://user-images.githubusercontent.com/34915727/84367186-715e2d00-ac06-11ea-8cbf-32f402595cbb.png)

这个得自己算了，通过已有path反推出path计算规则，然后再添加一个自定义图形就可以了。
