### ISSUE TITLE
升级到G6最新版本3.5.3后，绘制锚点方法报错问题。

### ISSUE THREAD

**Issue by wrh4585** [OXOYO/X-Flowchart-Vue#28]
目前在学习使用G6，大佬的项目功能强大，但是使用版本较老，G6更新较快，后续版本较3.1版本有变化。在将项目升级至3.5.3版本后，解决了运行报错，成功启动项目，但是拖动图标至画布时，图标的锚点计算方法报错（ shape.isPointInPath is not a function，将渲染方式改为svg后，可以出现锚点，但锚点显示有问题），未升级前尝试新增了几个svg图标，新增图标在画布中不绘制锚点，也不响应事件。看关闭的issue，大佬有更新G6版本的计划，想请教下怎么解决这些问题。

**Comment by OXOYO** [comment]
[dev](https://github.com/OXOYO/X-Flowchart-Vue/tree/dev) 分支已升级到3.5.x，整个分支目前还处于开发中，目前已完成如下工作：
1.针对G6 v3.5.x进行了适配升级；
2.修复了[v3.0.0[(https://github.com/OXOYO/X-Flowchart-Vue/tree/v3.0.0)的一些已知BUG；
3.优化工具栏、快捷键配置；
4.完善了属性面板；

G6还在不断更新，这边会保持适当的更新步伐，具体进度可以关注 [dev#TODO](https://github.com/OXOYO/X-Flowchart-Vue/tree/dev#todo)

**Comment by wrh4585** [comment]
是的呢，我在dev分支中看到了G6版本已经升级到3.5.1。我参考大佬的commit，进行了修改，但是还是存在问题，大佬的项目较为复杂，接触G6时间不长，还在摸索。。。本着不断改错不断学习的想法，对dev分支中所作的修改还未完全搞懂。多谢大佬的回复
