### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by cqyisbug** [OXOYO/X-Flowchart-Vue#3]
作者你好,我觉得你的东西很好,但是那个demo好像不能用,能更新下吗?谢谢啦

**Comment by OXOYO** [comment]
@cqyisbug 最近没时间搞这块，1.0.0分支正常可以先看看

**Comment by cqyisbug** [comment]
> @cqyisbug 最近没时间搞这块，1.0.0分支正常可以先看看
嗯嗯,谢谢.
