### ISSUE TITLE
导入json还有bug

### ISSUE THREAD

**Issue by zphtown** [OXOYO/X-Flowchart-Vue#32]

**Comment by OXOYO** [comment]
具体点

**Comment by zphtown** [comment]
1，随便拖拽几个图形
2，点击下载json
3，上传json
然后就会看到渲染的图形是乱的，问题出在upload方法
_t.editor.getNodes().forEach(node => { ... 这段代码，相信你找得到这个方法

**Comment by OXOYO** [comment]
了解，最近有点忙，欢迎pr。

**Comment by 905407220** [comment]
这个问题还没解决么？导入json拖动图形画面很卡
