### ISSUE TITLE
辅助网格错位

### ISSUE THREAD

**Issue by freedomdebug** [OXOYO/X-Flowchart-Vue#40]
![image](https://user-images.githubusercontent.com/7620476/105457050-2985a500-5cc1-11eb-86f4-6110ac0924f9.png)
 1920*1080
chrome 版本 87.0.4280.88（正式版本） （64 位）

![image](https://user-images.githubusercontent.com/7620476/105457175-576ae980-5cc1-11eb-9f20-9ac9699efd94.png)
jin'yong禁用g6的inset后正常

**Comment by SKT1yang** [comment]
找不到这段代码inset修改的地方
