### ISSUE TITLE
大佬 啥时在更新一版啊

### ISSUE THREAD

**Issue by bingyuea** [OXOYO/X-Flowchart-Vue#46]
buglist 的 bug依然很多，而且都是比较关键的bug，例如，撤回、上传json、写入文字就卡顿等等

**Comment by OXOYO** [comment]
暂无计划
官方出X6后这个意义就不大了，这一年1095的都没工夫更新了，后边看有没有计划修修BUG。

感谢持续关注，希望这个项目能给你带来些许帮助！
