### ISSUE TITLE
编辑带文本的矩形，设置文本大小后没有起作用，且样式shadowColor自动变化

### ISSUE THREAD

**Issue by lisenz** [OXOYO/X-Flowchart-Vue#48]
我在online的demo上试用，当我编辑带Text文本的矩形，将矩形中的文本的fontSize改变之后，并没有发生变化，反而是矩形的shadowColor发生了改变，请问是在线试用的程序的问题，还是本身组件存在bug？

**Comment by OXOYO** [comment]
可能是组件BUG

**Comment by lisenz** [comment]
online demo好像还是有那个问题，是修复了还未更新吗？
