### ISSUE TITLE
关于引用报错的问题

### ISSUE THREAD

**Issue by PKXZ** [OXOYO/X-Flowchart-Vue#59]
通过npm i @oxoyo/xfc --save进行安装
在界面引用后报错了：
import xfc from '@oxoyo/xfc'
import '@oxoyo/xfc/dist/xfc.css'

// 初始化
const xfcEditor = xfc({
    el: '#xfc'
})
![111](https://github.com/OXOYO/X-Flowchart-Vue/assets/18209468/2fc3b06b-7e43-43a0-a99a-2294a5cb9a87)
请问这个是什么原因导致的呢？

**Comment by PKXZ** [comment]
后来发现是vue.config.js里的svg规则导致的，添加以下单独处理即可
    config.module
      .rule('external-svg')
      .test(/\.svg$/)
      .exclude
      .add(resolve('src/assets')) 
      .end()
      .use('file-loader')
      .loader('file-loader')
      .options({
        name: 'img/[name].[hash:8].[ext]'
      });

**Comment by OXOYO** [comment]
V3版本仅供学习参考，当前的npm包不是最优方案
