### ISSUE TITLE
在Editor的index.vue中引入G6出现的问题

### ISSUE THREAD

**Issue by ljhtx** [OXOYO/X-Flowchart-Vue#6]
大神，您好！我在尝试将您的组件嵌入我自己的项目的时候，出现了一些问题。
  当我在Editor文件夹下的index.vue里import G6 from '@/global/g6/index'时，此时代码运行会出现
‘Model parse failed:Unexpected token
You may need an appropriate loader to handle this file type 
return{rotate:rad,...result}’
  我一开始以为是babel-loader版本落后的原因，将其更新至8.0.0后，仍然出现这种情况，而注释掉import G6 from '@/global/g6/index’代码就能正常运行，我想问一下，引入这个封装的包的时候是否要安装别的loader，或是改其他的配置文件。

**Comment by OXOYO** [comment]
不清楚你要做什么操作，`@/global/g6`是实现自定义交互、节点、边；`@/components/Editor`是实现编辑器的界面。

**Comment by ljhtx** [comment]
额，就是我自己新建了一个vue，想试着还原一下您的组件，ToolBar，Sketchpad，PanelLeft以及PanelRight组件的嵌入都没有问题，但是在还原编辑器的时候，也就是Editor/index.vue里的init函数里的new G6.Graph()
![image](https://user-images.githubusercontent.com/47860962/65583045-1c638380-dfb1-11e9-87ac-4578f3c206bd.png)
  这时候去引入global里的g6，再npm run dev，会出现：
![image](https://user-images.githubusercontent.com/47860962/65583183-56348a00-dfb1-11e9-894a-54221b9a6e92.png)
  不引入global的g6的话倒是完全可以运行，所以想问一下大神，是有什么特殊的配置吗？
  这是我的babel的配置：
![image](https://user-images.githubusercontent.com/47860962/65583483-e377de80-dfb1-11e9-8159-37cd18778dfb.png)

**Comment by OXOYO** [comment]
看上去是不支持ES6 解构赋值语法导致，修改下babel配置。

**Comment by SunKaedes** [comment]
我也出现这个问题了，请问解决了吗

**Comment by ljhtx** [comment]
可以去包里的把报错文件的那三个点去掉就可以了，不过我这个只是临时的办法，实际上应该是加载方式的问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sunqiang0914 <notifications@github.com&gt;
发送时间: 2020年4月1日 14:44
收件人: OXOYO/X-Flowchart-Vue <X-Flowchart-Vue@noreply.github.com&gt;
抄送: ljhtx <502538529@qq.com&gt;, Manual <manual@noreply.github.com&gt;
主题: 回复：[OXOYO/X-Flowchart-Vue] 在Editor的index.vue中引入G6出现的问题 (#6)





 
我也出现这个问题了，请问解决了吗
